apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dispatch.player.dev.ubivius.tk
spec:
  secretName: dispatch.player.dev.ubivius.tk
  dnsNames:
  - dispatch.player.dev.ubivius.tk
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
